# Generated by Django 3.0.5 on 2020-04-10 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'managed': False},
        ),
    ]
